# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./cmd/grubstation
    ldflags:
      - -s -w -X github.com/jjack/grubstation/internal/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - arm64
      - amd64
      - "386"
    hooks:
      post:
        - cmd: >-
            {{ if eq .Os "windows" }}
              wix build -nologo -ext WixToolset.UI.wixext -ext WixToolset.Firewall.wixext -ext WixToolset.Util.wixext -culture en-US -d Version={{.Version}} -d BinaryPath="{{ .Path }}" -arch {{ if eq .Arch "amd64" }}x64{{ else if eq .Arch "arm64" }}arm64{{ else }}x86{{ end }} -o "../../dist/grubstation_{{.Version}}_{{.Os}}_{{.Arch}}.msi" "../../.build/windows/template.wxs" "../../.build/windows/localization.wxl"
            {{ else }}
              go version
            {{ end }}
          dir: "{{ dir .Path }}"

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - homepage: "https://github.com/jjack/grubstation"
    maintainer: "jjack"
    description: "Agent to manage bare-metal OS booting via Home Assistant and WOL"
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk
    scripts:
      postremove: .build/linux/postremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
